const fs = require('fs');
const path = require('path');

console.log('Icon Resize Helper');
console.log('==================');
console.log('');
console.log('Your current icon is 255x256 pixels');
console.log('Windows icons work best at exactly 256x256 pixels');
console.log('');
console.log('To fix this:');
console.log('');
console.log('Option 1: Use an image editor');
console.log('1. Open public/Logo.ico in an image editor');
console.log('2. Resize to exactly 256x256 pixels');
console.log('3. Save as ICO format');
console.log('');
console.log('Option 2: Use online tools');
console.log('1. Go to https://www.icoconverter.com/');
console.log('2. Upload your Logo.ico file');
console.log('3. Set size to 256x256 pixels');
console.log('4. Download the resized ICO file');
console.log('5. Replace public/Logo.ico with the new file');
console.log('');
console.log('Option 3: Use GIMP/Photoshop');
console.log('1. Open Logo.ico');
console.log('2. Image → Scale Image');
console.log('3. Set to 256x256 pixels');
console.log('4. Export as ICO');
console.log('');
console.log('After resizing:');
console.log('1. Replace public/Logo.ico with 256x256 version');
console.log('2. Run: npm run dist:portable');
console.log('3. Check the executable icon');
console.log('');
console.log('Current icon dimensions: 255x256');
console.log('Required dimensions: 256x256'); 